package com.example.supplychain;
import java.sql.*;

public class DatabaseConnection {
    private static final String DB_URL = "jdbc:mysql://localhost:3306/supply_chain";
    private static final String USER = "root";
    private static final String PASS = "@Rohit$4331&";

    // Statement is a class , it helps to execute(or run) the query to the database .
    public Statement getStatement(){
        Statement statement = null;
        Connection conn;
        try{
            conn = DriverManager.getConnection(DB_URL,USER,PASS);   // establish the connection to the database
            statement = conn.createStatement();
        }catch(Exception e){
            e.printStackTrace();
        }

        return statement;
    }

    public ResultSet getQueryTable(String query){
        Statement statement = getStatement();
        try{
            //it is usually generated by executing a statement that queries the database.
            return statement.executeQuery(query);    // return the resultset by apply query on statement

        }catch(Exception e){
            e.printStackTrace();
        }
        return null;
    }

    public int insertData(String query){
        Statement statement = getStatement();
        try{
            //it is usually generated by executing a statement that queries the database.
            return statement.executeUpdate(query);    // return the resultset by apply query on statement

        }catch(Exception e){
            e.printStackTrace();
        }
        return 0;
    }

    public static void main(String[] args) {
        DatabaseConnection dbConn = new DatabaseConnection();

        String query = "SELECT * FROM customer";
        ResultSet rs = dbConn.getQueryTable(query);      // Run a getQueryTable method by apply quary to db and return the the table of data.
        try{
            while(rs != null && rs.next()){
                System.out.println("Fetched Result");
                System.out.println("Cid : " + rs.getInt("c_id") +
                                "  Name : " + rs.getString("first_name") +
                                "  Email: " + rs.getString("email")
                                 );
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }



}
